"""Parity check (Python side): replay the JS reference corpus through the
Python rules port and assert byte-for-byte agreement.

The corpus is generated by `parity_corpus.mjs` and lives at
`training/parity_expected.json` (gitignored — regenerate by running the JS
script). JS is the source of truth; this script is the dependency direction
we care about.

Run from the training/ directory:
    python scripts/parity_check.py
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
TRAINING_DIR = HERE.parent
sys.path.insert(0, str(TRAINING_DIR))

from games.holdem import (  # noqa: E402
    apply_action,
    calculate_pots,
    calculate_showdown_pots,
    legal_actions,
    start_new_hand,
)
from games.hand_evaluator import evaluate_hand  # noqa: E402


CORPUS_PATH = TRAINING_DIR / "parity_expected.json"


# ── State comparison ──────────────────────────────────────────────


# Snapshot fields the parity check enforces. Matches snapshotState() in
# parity_corpus.mjs exactly.
SNAPSHOT_FIELDS = (
    "handNumber",
    "phase",
    "communityCards",
    "players",
    "pots",
    "totalPot",
    "dealerSeat",
    "actionOnSeat",
    "lastAggressorSeat",
    "currentStreetBet",
    "lastRaiseSize",
    "callAmount",
    "canCheck",
    "minRaiseAmount",
    "maxRaiseAmount",
    "winners",
)

PLAYER_FIELDS = (
    "seat",
    "name",
    "isHuman",
    "chips",
    "status",
    "holeCards",
    "currentBet",
    "totalBetThisHand",
    "hasActedThisStreet",
    "isDealer",
    "isSB",
    "isBB",
    "handRank",
    "handKickers",
)


def project(state, fields):
    return {f: state.get(f) for f in fields}


def project_state(state):
    snap = project(state, SNAPSHOT_FIELDS)
    snap["players"] = [project(p, PLAYER_FIELDS) for p in snap["players"]]
    # Drop the deck — not part of the snapshot.
    return snap


def assert_state_eq(actual, expected, context):
    py_snap = project_state(actual)
    if py_snap != expected:
        diff_lines = _diff(py_snap, expected)
        raise AssertionError(
            f"state mismatch at {context}:\n" + "\n".join(diff_lines[:60])
        )


def _diff(a, b, path=""):
    """Return a list of human-readable difference lines for two nested dicts."""
    lines = []
    if isinstance(a, dict) and isinstance(b, dict):
        keys = set(a.keys()) | set(b.keys())
        for k in sorted(keys):
            lines.extend(_diff(a.get(k), b.get(k), f"{path}.{k}" if path else k))
    elif isinstance(a, list) and isinstance(b, list):
        if len(a) != len(b):
            lines.append(f"{path}: list length {len(a)} != {len(b)}")
        for i in range(max(len(a), len(b))):
            ai = a[i] if i < len(a) else "<MISSING>"
            bi = b[i] if i < len(b) else "<MISSING>"
            lines.extend(_diff(ai, bi, f"{path}[{i}]"))
    elif a != b:
        lines.append(f"{path}: py={a!r} js={b!r}")
    return lines


# ── Checks ────────────────────────────────────────────────────────


def check_hand_evaluator(cases):
    for i, c in enumerate(cases):
        actual = evaluate_hand(c["cards"])
        if actual != c["expected"]:
            raise AssertionError(
                f"handEvaluator case {i}: py={actual!r} js={c['expected']!r}\n"
                f"  cards: {c['cards']}"
            )
    print(f"  handEvaluator: {len(cases)} cases OK")


def check_pot_calculator(cases):
    for i, c in enumerate(cases):
        actual_pots = calculate_pots(c["players"])
        actual_show = calculate_showdown_pots(c["players"])
        if actual_pots != c["expectedPots"]:
            raise AssertionError(
                f"calculatePots case {i}: py={actual_pots!r} js={c['expectedPots']!r}"
            )
        if actual_show != c["expectedShowdownPots"]:
            raise AssertionError(
                f"calculateShowdownPots case {i}: py={actual_show!r} "
                f"js={c['expectedShowdownPots']!r}"
            )
    print(f"  potCalculator: {len(cases)} cases OK")


def check_legal_actions(cases):
    for i, c in enumerate(cases):
        actual = legal_actions(c["state"])
        if actual != c["expected"]:
            raise AssertionError(
                f"legalActions case {i}: py={actual!r} js={c['expected']!r}\n"
                f"  state.phase={c['state']['phase']} actor={c['state']['actionOnSeat']}"
            )
    print(f"  legalActions: {len(cases)} cases OK")


def check_trials(trials):
    total_hands = 0
    total_transitions = 0
    for trial in trials:
        # Each trial starts from a fresh `createGame()`. JS recorded the
        # state ABEFORE startNewHand — that's `preStartState`. We feed it
        # into start_new_hand along with the recorded deck.
        prev = trial["hands"][0]["preStartState"] if trial["hands"] else None
        for hand in trial["hands"]:
            state = start_new_hand(hand["preStartState"], deck=hand["deck"])
            assert_state_eq(
                state,
                hand["postStartState"],
                f"trial {trial['trialIndex']} hand {hand['handIndex']} after startNewHand",
            )
            for ti, tr in enumerate(hand["transitions"]):
                state = apply_action(state, tr["action"])
                assert_state_eq(
                    state,
                    tr["afterState"],
                    f"trial {trial['trialIndex']} hand {hand['handIndex']} "
                    f"transition {ti} action={tr['action']!r}",
                )
                total_transitions += 1
            total_hands += 1
    print(
        f"  trials: {len(trials)} ({total_hands} hands, "
        f"{total_transitions} transitions) OK"
    )


# ── Main ──────────────────────────────────────────────────────────


def main():
    if not CORPUS_PATH.exists():
        print(
            f"corpus missing at {CORPUS_PATH}\n"
            f"run: node training/scripts/parity_corpus.mjs",
            file=sys.stderr,
        )
        sys.exit(2)

    print(f"loading corpus from {CORPUS_PATH}")
    with open(CORPUS_PATH) as f:
        payload = json.load(f)

    print(f"checking parity (corpus seed={payload['meta']['seed']})")
    check_hand_evaluator(payload["handEvaluator"])
    check_pot_calculator(payload["potCalculator"])
    check_trials(payload["trials"])
    check_legal_actions(payload["legalActions"])
    print("ALL PARITY CHECKS PASSED")


if __name__ == "__main__":
    main()
