"""Heuristic parity check (Python side).

Loads the corpus generated by `parity_heuristic.mjs` and asserts that the
Python heuristic produces byte-identical equity and chosen actions given
the same state and seed.

LCG math is integer-stable across both languages; equity is a sum of
identical-precision floats divided by an identical integer count, so we
expect exact equality (not just "close to"). We allow a tiny tolerance
for double-precision rounding just in case.

Run from training/:
    python scripts/parity_heuristic.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
TRAINING_DIR = HERE.parent
sys.path.insert(0, str(TRAINING_DIR))

from heuristic import LCG, choose_action_idx  # noqa: E402
from heuristic import equity as eq_fn  # noqa: E402
from games.holdem import _action_for_idx  # noqa: E402


CORPUS_PATH = TRAINING_DIR / "parity_heuristic_expected.json"

EQUITY_TOL = 1e-12


def main():
    if not CORPUS_PATH.exists():
        print(
            f"corpus missing at {CORPUS_PATH}\n"
            f"run: node training/scripts/parity_heuristic.mjs",
            file=sys.stderr,
        )
        sys.exit(2)

    with open(CORPUS_PATH) as f:
        payload = json.load(f)

    cases = payload["cases"]
    print(f"loaded {len(cases)} heuristic cases")

    eq_mismatches = 0
    idx_mismatches = 0
    action_mismatches = 0
    max_eq_delta = 0.0

    for i, c in enumerate(cases):
        rng = LCG(c["seed"])
        actual_eq = eq_fn(c["state"], c["seat"], c["numSamples"], rng)
        actual_idx = choose_action_idx(c["state"], actual_eq)
        actual_action = _action_for_idx(c["state"], actual_idx)

        delta = abs(actual_eq - c["expectedEquity"])
        if delta > max_eq_delta:
            max_eq_delta = delta
        if delta > EQUITY_TOL:
            eq_mismatches += 1
            if eq_mismatches <= 3:
                print(
                    f"  case {i}: equity py={actual_eq!r} js={c['expectedEquity']!r} "
                    f"delta={delta:.3e}"
                )

        if actual_idx != c["expectedActionIdx"]:
            idx_mismatches += 1
            if idx_mismatches <= 3:
                print(
                    f"  case {i}: action idx py={actual_idx} js={c['expectedActionIdx']} "
                    f"(eq py={actual_eq:.6f} js={c['expectedEquity']:.6f})"
                )

        if actual_action != c["expectedAction"]:
            action_mismatches += 1
            if action_mismatches <= 3:
                print(
                    f"  case {i}: action py={actual_action!r} js={c['expectedAction']!r}"
                )

    print(f"max equity delta: {max_eq_delta:.3e} (tol {EQUITY_TOL:.0e})")
    print(f"equity mismatches:    {eq_mismatches}/{len(cases)}")
    print(f"action-idx mismatches: {idx_mismatches}/{len(cases)}")
    print(f"action mismatches:     {action_mismatches}/{len(cases)}")
    if eq_mismatches or idx_mismatches or action_mismatches:
        sys.exit(1)
    print("ALL HEURISTIC PARITY CHECKS PASSED")


if __name__ == "__main__":
    main()
